spring: 
  profiles: 
    active:
    - dev
---

spring: 
  profiles: dev
  application:
    name: springcloudparent-config-dev

---

spring: 
  profiles: test
  application:
    name: springcloudparent-config-test

# 请保存为UTF-8格式